# SPACEFISH OPTIONS

# [spacefish](https://github.com/matchai/spacefish)

# prompt
set SPACEFISH_CHAR_SYMBOL "❯"
set SPACEFISH_PROMPT_DEFAULT_PREFIX ""
set SPACEFISH_PROMPT_ORDER user host dir git node pyenv docker kubecontext aws time exec_time line_sep venv char

# dir
set SPACEFISH_DIR_COLOR 999
set SPACEFISH_DIR_PREFIX ""
set SPACEFISH_DIR_TRUNC_REPO false

# git
set SPACEFISH_GIT_PREFIX ""
set SPACEFISH_GIT_SYMBOL ""

set SPACEFISH_GIT_BRANCH_COLOR 666

set SPACEFISH_GIT_STATUS_COLOR 666
set SPACEFISH_GIT_STATUS_PREFIX ""
set SPACEFISH_GIT_STATUS_SUFFIX ""

# node
# using defaults...

# pyenv
# using defaults...

# docker
set SPACEFISH_DOCKER_COLOR 666
set SPACEFISH_DOCKER_PREFIX "["
set SPACEFISH_DOCKER_SUFFIX "]"
set SPACEFISH_DOCKER_SYMBOL ""

# kubecontext
set SPACEFISH_KUBECONTEXT_COLOR 666
set SPACEFISH_KUBECONTEXT_NAMESPACE_SHOW false
set SPACEFISH_KUBECONTEXT_PREFIX "["
set SPACEFISH_KUBECONTEXT_SUFFIX "]"
set SPACEFISH_KUBECONTEXT_SYMBOL ""

# aws
set SPACEFISH_AWS_COLOR 666
set SPACEFISH_AWS_PREFIX "["
set SPACEFISH_AWS_SUFFIX "]"
set SPACEFISH_AWS_SYMBOL ""

# time
set SPACEFISH_TIME_COLOR 666
set SPACEFISH_TIME_PREFIX " "
set SPACEFISH_TIME_SHOW true

# venv
set VIRTUAL_ENV_DISABLE_PROMPT true
set SPACEFISH_VENV_GENERIC_NAMES ""
set SPACEFISH_VENV_SYMBOL ""
set SPACEFISH_VENV_COLOR 666

