sudo: false

language: node_js

node_js:
  - "10"
  - "9"

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn
  - yarn run vscode:prepublish

script:
  - yarn test

notifications:
  slack: karigarihq:wyMAff0ihz5w5H2UKtrU2etP
